### ISSUE TITLE
Handle opencog writing to source directory which is read-only in nix

### ISSUE THREAD

**Issue by Radivarig** [opencog/opencog-nix#1]
Redirect locations of new directories/files to $out instead of current source directory

```
Install the project...
-- Install configuration: "Release"
...
Make Error at opencog/learning/PatternMiner/types/cmake_install.cmake:73 (file):
  file cannot create directory:
  /nix/store/hkqfbp18drmkc6lx996kv2kyn3xyca7p-source/scm/opencog/patternminer.
  Maybe need administrative privileges.
...
```

**Comment by linas** [comment]
Somewhat confused .. I'm pretty sure that `make install` should not be writing to the source dirs. In fact neither cmake nor make should write tot he source dirs ... if they are, a bug should be opened against that component.

**Comment by Radivarig** [comment]
Hm, "source" was coincidental since I've set DATADIR to be the cogutil source as that is where I found cmake folder with files required in [opencog/CMakeLists.txt:523](https://github.com/opencog/opencog/blob/49368962ffd4dbea6fabbc152e81ca4b849db9fa/CMakeLists.txt#L523), `OpenCogMacros.cmake` and `OpenCogFunctions.cmake`.

Otherwise if not defined, DATADIR gets set from [opencog/CMakeLists.txt:514](https://github.com/opencog/opencog/blob/49368962ffd4dbea6fabbc152e81ca4b849db9fa/CMakeLists.txt#L514) to `${CMAKE_INSTALL_PREFIX}/share/opencog` where CMAKE_INSTALL_PREFIX is $out - a fresh directory of the nix build.

The problem is that the same DATADIR is the location where [opencog/learning/PatternMiner/types/CMakeLists.txt:41](https://github.com/opencog/opencog/blob/a19ff7eaa1904307f0397678e76565d610735095/opencog/learning/PatternMiner/types/CMakeLists.txt#L41) writes to.

I've worked around by copying cmake folder to the $out dir.

**Comment by linas** [comment]
In the last few days, `OpenCogMacros.cmake` and `OpenCogFunctions.cmake` and a third file were moved out of cogutil, and to the atomspace. They should never have gone into cogutil, that was an accident from earlier in the summer.

I'm not sure of DATADIR is used as a location to put things, or a location to get things from.  If its used for both, that seems like a problem for nix, but its fixable we should probably define a DATA_INSTALL_DIR or DATA_INSTALL_PREFIX or something like that.  For traditional users, it could be the same as DATADIR, but for NIX it could be different; a pull req to do that would be reasonable and acceptable.
