### ISSUE TITLE
Research cause of having to sleep after psql database creation

### ISSUE THREAD

**Issue by Radivarig** [opencog/opencog-nix#15]
Had to add `sleep 0.1` after starting the `pg_ctl start ...` otherwise there would be a `template1` error when creating a user immediately afterwards. [relevant](https://github.com/opencog/opencog-nix/pull/13#discussion_r275565004)

**Comment by linas** [comment]
Try the `-w` flag -- So `pg_ctl start` is starting up the postgres server, and I can see that this might take fractions of a second for empty databases, but could take seconds or even minutes for large databases.  "It would be nice" if it did not return until the server is started.

Hmm. `man pg_ctl` shows:
```
       -w
           Wait for the startup or shutdown to complete. Waiting is the
           default option for shutdowns, but not startups. When waiting for
           startup, pg_ctl repeatedly attempts to connect to the server. When
           waiting for shutdown, pg_ctl waits for the server to remove its PID
           file. This option allows the entry of an SSL passphrase on startup.
           pg_ctl returns an exit code based on the success of the startup or
           shutdown.

       -W
           Do not wait for startup or shutdown to complete. This is the
           default for start and restart modes.
```

It also recommends redirecting output to a log file either by redirecting stdout or using the `-l` flag.

**Comment by Radivarig** [comment]
`-w` works :)
