### ISSUE TITLE
Handle "cache" for auto generated files during check phase

### ISSUE THREAD

**Issue by Radivarig** [opencog/opencog-nix#16]
```
;;; note: auto-compilation is enabled, set GUILE_AUTO_COMPILE=0
;;;       or pass the --no-auto-compile argument to disable.
;;; compiling /.../opencog/scm/opencog/base/core_types.scm
;;; WARNING: compilation of /.../opencog/scm/opencog/base/core_types.scm failed:
;;; failed to create path for auto-compiled file "/..."
...
```
No cache folders in nix, only read-only store. Create a tmp folder and set `XDG_CACHE_HOME` to it.

**Comment by linas** [comment]
Careful calling it, thinking about it as a "cache" -- its a lot like libblahblah.so being a "cache" for C/C++ code, java_blah.jar being a cache for java code, blah.pyc being a cache for python code.  They're all compiled binaries.  Bytecode for java, python and guile, machinecode for C/C++.

viz you want to treat it as real compiled code -- you don't want to wait for the autocompile to run every time the user starts up the process.

**Comment by Radivarig** [comment]
> viz you want to treat it as real compiled code -- you don't want to wait for the autocompile to run every time the user starts up the process.

I think this here is only needed during the check phase. I've renamed the title

**Comment by linas** [comment]
If you don't keep the `/home/user/.cache/guile` directory, then it will be rebuilt every time, and that rebuild can take 5-10 seconds or longer,, and it can be annoying.

**Comment by Radivarig** [comment]
> If you don't keep the `/home/user/.cache/guile` directory, then it will be rebuilt every time, and that rebuild can take 5-10 seconds or longer,, and it can be annoying.

This is only needed when building the package during the check phase which does not have access to home folder.
When running the build result with `nix-shell` which has access to it, `/home/user/.cache/guile` does get used.
