### ISSUE TITLE
[cogserver] ShellUTest sometimes fails (corrupted size vs. prev_size)

### ISSUE THREAD

**Issue by Radivarig** [opencog/opencog-nix#40]
`ShellUTest` fails more often than it doesn't, so I disabled it.
The issue is already described [here](https://github.com/opencog/cogserver/issues/5)

**Comment by linas** [comment]
On my system, I can run this test 19x per hour, all of them pass.

**Comment by linas** [comment]
OK, so its a boost bug .. with boost 1.62 I find that 30 tests out of 30 pass. 

With boost 1.67 I get 5 failures out of 24 runs...

Have to ponder how to get to a working version of boost ...  since apparently older packages are not generally available ...

**Comment by Radivarig** [comment]
It's working with `boost162` at least 5 times in a row that I've tested. It takes me ~200s to complete though. Am I missing some config like with atomspace LargeFlatUTest?

**Comment by linas** [comment]
I think there is a 200sec timer in there, because it always takes that long, no matter what. It's meant to take a long time, under the assumption that race conditions, if present, are rare.
