### ISSUE TITLE
Handle .scm and .so paths better

### ISSUE THREAD

**Issue by Radivarig** [opencog/opencog-nix#45]
Currently, I'm discovering and adding by hand to `GUILE_LOAD_PATH` and `LD_LIBRARY_PATH` in the `patchPhase` the missing shared files paths when something breaks.

Here is an example of which search paths are generated when a module is not found [in this comment](https://github.com/opencog/opencog-nix/issues/44#issuecomment-560149313).

It seems that because of these paths being guessed on the fly, some modules can be imported from multiple locations like `libagents.so`, while being exported to `${cogserver}/lib/opencog/modules/libagents.so`, it's being imported with and without `agents` folder:
```bash
λ grep -rn -e "libagents.so"
attention/opencog/attention/AttentionModule.cc:75:    config().set("MODULES", "agents/libagents.so");
attention/tests/attention/HebbianCreationModuleUTest.cxxtest:67:        config().set("MODULES", "libagents.so");
attention/tests/attention/ImportanceDiffusionUTest.cxxtest:107:    config().set("MODULES", "libagents.so");
cogserver/opencog/cogserver/modules/python/PythonModule.cc:66:	config().set("MODULES", "agents/libagents.so");
```
I thought maybe finding shared files paths from `<package>/lib` or `<package>/share` folders and generating a list of their parent folders up to the base dir would cover all cases, but here `libagents.so` is not in `agents` folder of `${cogserver}/lib/opencog/modules`:
```
λ ls -R lib/opencog/
lib/opencog/:
libguile-cogserver.so  libnetwork.so  libserver.so  modules

lib/opencog/modules:
libagents.so  libbuiltinreqs.so  libpy-shell.so  libPythonModule.so  libscheme-shell.so
```

**Comment by linas** [comment]
The `config().set()` settings do indeed look messy ad-hoc.

The `ls -R` listing looks exactly correct: the first batch are "ordinary" shared libs; the "modules" are shared libs with additional stuff in them that the cogserver c++ module loader knows how to load.  Besides those five, I think maybe one of the attention ones is a formal module.

I'm discouraging the creation of new opencog c++ modules; for maintainability, its just seems better if scheme or python modules are created instead.  Less muss, less fuss, better API's,  that way. These five plus a few more, are legacy...

**Comment by Radivarig** [comment]
I've replaced all manual extending of environment with `helpers/extend-env.nix` that automatically detects all folders and their parents up to the dependency base path for a list of dependencies, that include `.scm` and `.so` and extend `GUILE_LOAD_PATH`, `LD_LIBRARY_PATH` and `PYTHONPATH`.

For example, adding this to `patchPhase`:
`${import ../helpers/extend-env.nix {paths = [ atomspace ];}}`

will extend `GUILE_LOAD_PATH` with:
```
/nix/store/...-atomspace
/nix/store/...-atomspace/share
/nix/store/...-atomspace/share/guile
/nix/store/...-atomspace/share/guile/site
/nix/store/...-atomspace/share/guile/site/opencog
/nix/store/...-atomspace/share/guile/site/opencog/atoms
/nix/store/...-atomspace/share/guile/site/opencog/atoms/atom_types
/nix/store/...-atomspace/share/guile/site/opencog/base
/nix/store/...-atomspace/share/guile/site/opencog/matrix
/nix/store/...-atomspace/share/guile/site/opencog/sheaf
```
and `LD_LIBRARY_PATH` and `PYTHONPATH` with:
```
/nix/store/...-atomspace
/nix/store/...-atomspace/lib
/nix/store/...-atomspace/lib/opencog
/nix/store/...-atomspace/share
/nix/store/...-atomspace/share/python3.6
/nix/store/...-atomspace/share/python3.6/site-packages
/nix/store/...-atomspace/share/python3.6/site-packages/opencog
```

**Comment by linas** [comment]
I'm confused.  This should be enough:
```
/nix/store/.../share/guile/site
```
since guile will know how to find the rest from there.  adding more paths might lead to confusion.

Similarly for the library paths: pointing at the `lib/opencog` path should be enough, the linker-loader should be able to handle things from there.

**Comment by Radivarig** [comment]
I've finally found that the root issue was with `.so` files which on their own (without extending `LD_LIBRARY_PATH`) had `not found` messages in `ldd -r *.so` output,  so after the install phase I added rpaths with `patchelf`:
```sh
  postFixup = ''
    addToRPath="$addToRPath:$out/lib/opencog"
    addToRPath="$addToRPath:$out/${PYTHON_DEST}/opencog"

    for file in $(find $out/lib -type f -executable); do
      rpath=$(patchelf --print-rpath $file)
      patchelf --set-rpath "$rpath:$addToRPath" $file
    done
  '';
```
Now this overkill is not needed! I've further cleaned up the code.
