### ISSUE TITLE
[attention] AttentionParamQueryUTest fails (Expected ("0" == _atq.get_param_value(params[0])), found (0 != ""))

### ISSUE THREAD

**Issue by Radivarig** [opencog/opencog-nix#49]
I've tried these values as well and get:
```json
false: "",
true: "1",
0: "",
"0": "",
"": "",
23: "23",
```
```
7/9 Test #7: AttentionParamQueryUTest .........***Failed    0.86 sec
Running cxxtest tests (4 tests)..
In AttentionParamQueryUTest::test_set_param:
/build/source/build/tests/attention/../../../tests/attention/AttentionParamQueryUTest.cxxtest:81: Error: Expected ("0" == _atq.get_param_value(params[0])), found (0 != "")
```

**Comment by linas** [comment]
~~?  Didn't we previously decide that this failure was due to some inconsistency between the version of cotutils, atomspace and cogserver? I thought you fixed it by doing a git pull on each, and rebuilding.  Why has this bug come back?~~

**Comment by linas** [comment]
Oh, I'm getting this error too, now. Problem is opencog/atomspace#2380 has not been merged and so there are breaking changes...

**Comment by linas** [comment]
actually, I don't know what broke this. The original code was just insane; I removed the insanity and now it works.
