### ISSUE TITLE
[atomspace] cxxtest fails with unbound variable

### ISSUE THREAD

**Issue by Radivarig** [opencog/opencog-nix#7]
Currently `atomspace` check fails with
```
...
 14/121 Test  #14: FreeLinkUTest ....................   Passed    0.85 sec
        Start  15: MapLinkUTest
 15/121 Test  #15: MapLinkUTest .....................***Failed    1.34 sec
...
ERROR: In procedure apply-smob/1:
Unbound variable: cog-execute!
ABORT: unbound-variable
```
In this [shell.nix](https://github.com/opencog/opencog-nix/blob/master/opencog/shell.nix#L22) I've added `<atomspace_folder>/share/opencog/scm` to guile load path as suggested from [atomspace#87](https://github.com/opencog/atomspace/issues/87) to avoid this issue.

Not sure where should I add this for cxxtest files that evaluate guile code.

Where do these get the reference to scm folder when not built with nix if it is not added to load path from within eval?

**Comment by linas** [comment]
https://www.gnu.org/software/guile/manual/html_node/Load-Paths.html  says this:

> The GUILE_LOAD_PATH environment variable can be used to prepend or append additional directories (see Environment Variables).

so I guess `GUILE_LOAD_PATH=<atomspace_folder>/share/opencog/scm make test`  should work?

**Comment by Radivarig** [comment]
Yes, that is what I've used. Now I also see it was loading correctly with `logger().debug(eval->eval("%load-path"));`. 

The problem seems to be with making "*.so" files available.

This is the output from `logger().debug(eval->eval("(use-modules (opencog exec))"));`.
```
ERROR: In procedure apply-smob/1:
In procedure dynamic-link: file: "libexec", message: "file not found"
ABORT: misc-error
```

Which is located here `build/opencog/atoms/libexec.so`.

**Comment by Radivarig** [comment]
Documentation for loading guile extension mentions that these will be looked up in `LTDL_LIBRARY_PATH` which reminded me of this [comment](https://github.com/opencog/opencog-nix/issues/3#issuecomment-445103488) meaning I have to use `LD_LIBRARY_PATH`. I just tried it and it works :) but I had to reference direct parent folders of the `.so`.

When the atomspace installation is done, it creates `/nix/store/...-atomspace/lib/opencog` folder with all the `*.so` files which is the folder I am referencing from opencog nix-shell [here](https://github.com/opencog/opencog-nix/blob/5972a9ee8e43074ba74e06ce0a5a83f6e020e0d9/opencog/shell.nix#L16).

Will look into how this gets done to avoid scooping up the files manually after the build phase.

**Comment by Radivarig** [comment]
Had to also set guile cache folder #16
